### ISSUE TITLE
School page

### ISSUE THREAD

**Issue by anjoelus** [forntoh/MBOASSIKOLOPATH#11]
1. It takes around 1 - 2 minutes to load data. It is better to load and display data sequentially.
2. When you open a school and you come back to the shcool page, it takes again 1 - 2 min to load all the data. The UX is not good.

**Comment by forntoh** [comment]
The first time Schools and Job takes about 15s to load but after that, they take barely 5s to load. That's much improved from the previous version, it's not actually a bug, I'll keep optimizing the load times in subsequent versions.
