### ISSUE TITLE
Job page

### ISSUE THREAD

**Issue by anjoelus** [forntoh/MBOASSIKOLOPATH#12]
1. It takes around 1 - 2 minutes to load data. It is better to load and display data sequentially.
2. The app crashes when you open a serie

**Comment by forntoh** [comment]
I didn't experience any crash in the three devices I tested in. For me to know the issue you face, please use Android Studio to collect the error logs.

**Comment by forntoh** [comment]
> I didn't experience any crash in the three devices I tested in. For me to know the issue you face, please use Android Studio to collect the error logs.

Follow this [How to get logs from your Android device](https://help.testlio.com/en/articles/129738-how-to-get-logs-from-your-android-device)
