### ISSUE TITLE
Sector page

### ISSUE THREAD

**Issue by anjoelus** [forntoh/MBOASSIKOLOPATH#13]
1. the app crashes when you open "enseignement general" or "enseignement technique
2. Formation professionnelle is empty
3. same for after primary school and after the first cycle menus

**Comment by forntoh** [comment]
@anjoelus  It works well on Samsung Galaxy S8 (9.0), Tecno F1 (8.1) and emulator with Android 9 installed, you data connection needs to be stable when you first launch the app to download the database

**Comment by anjoelus** [comment]
@forntoh check the attached log file.
[log.TXT](https://github.com/forntoh/MBOASSIKOLOPATH/files/4665404/log.TXT)
The error persists

**Comment by forntoh** [comment]
Fixed in this commit 9ad2af2
